export const resonators = [
  {
    id: "rover",
    name: "Rover",
    element: "Spectro",
    rarity: 5,
    weapon: "Sword",
    description:
      "A mysterious individual who awakened from a long slumber. Their past remains shrouded in mystery, but their determination to uncover the truth drives them forward.",
    baseStats: {
      hp: 912,
      attack: 21,
      defense: 109,
      critRate: 5,
      critDMG: 150,
    },
    skills: {
      basic: {
        name: "Resonating Slashes",
        type: "Basic Attack",
        description: "Rover performs up to 5 consecutive attacks, dealing Spectro DMG.",
        multipliers: [
          { level: 1, values: { stage1: 43.2, stage2: 40.8, stage3: 51.6, stage4: 25.2, stage5: 79.2 } },
          { level: 2, values: { stage1: 46.7, stage2: 44.1, stage3: 55.8, stage4: 27.3, stage5: 85.7 } },
          { level: 3, values: { stage1: 50.2, stage2: 47.4, stage3: 60.0, stage4: 29.4, stage5: 92.2 } },
          { level: 4, values: { stage1: 55.1, stage2: 52.0, stage3: 65.9, stage4: 32.3, stage5: 101.3 } },
          { level: 5, values: { stage1: 58.6, stage2: 55.3, stage3: 70.1, stage4: 34.4, stage5: 107.8 } },
          { level: 6, values: { stage1: 62.8, stage2: 59.2, stage3: 75.1, stage4: 36.8, stage5: 115.5 } },
          { level: 7, values: { stage1: 68.4, stage2: 64.5, stage3: 81.8, stage4: 40.1, stage5: 125.8 } },
          { level: 8, values: { stage1: 74.0, stage2: 69.8, stage3: 88.5, stage4: 43.4, stage5: 136.1 } },
          { level: 9, values: { stage1: 79.6, stage2: 75.1, stage3: 95.2, stage4: 46.7, stage5: 146.4 } },
          { level: 10, values: { stage1: 85.8, stage2: 80.9, stage3: 102.6, stage4: 50.3, stage5: 157.7 } },
        ],
      },
      heavy: {
        name: "Resonating Spin",
        type: "Heavy Attack",
        description: "Rover consumes Stamina to attack the target, dealing Spectro DMG.",
        multipliers: [
          { level: 1, values: { damage: 62.5 } },
          { level: 2, values: { damage: 67.6 } },
          { level: 3, values: { damage: 72.7 } },
          { level: 4, values: { damage: 79.8 } },
          { level: 5, values: { damage: 84.9 } },
          { level: 6, values: { damage: 91.0 } },
          { level: 7, values: { damage: 99.1 } },
          { level: 8, values: { damage: 107.2 } },
          { level: 9, values: { damage: 115.3 } },
          { level: 10, values: { damage: 124.4 } },
        ],
      },
      skill: {
        name: "Waveshock",
        type: "Resonance Skill",
        description: "Rover launches an attack forward, dealing Spectro DMG. Can be cast in mid-air.",
        multipliers: [
          { level: 1, values: { damage: 142.8 } },
          { level: 2, values: { damage: 154.4 } },
          { level: 3, values: { damage: 166.0 } },
          { level: 4, values: { damage: 182.2 } },
          { level: 5, values: { damage: 193.8 } },
          { level: 6, values: { damage: 207.5 } },
          { level: 7, values: { damage: 226.1 } },
          { level: 8, values: { damage: 244.7 } },
          { level: 9, values: { damage: 263.3 } },
          { level: 10, values: { damage: 284.0 } },
        ],
      },
      liberation: {
        name: "Echoing Orchestra",
        type: "Resonance Liberation",
        description: "Rover deals Spectro DMG to surrounding enemies and enters Resonance state.",
        multipliers: [
          { level: 1, values: { damage: 571.2 } },
          { level: 2, values: { damage: 618.0 } },
          { level: 3, values: { damage: 664.8 } },
          { level: 4, values: { damage: 730.1 } },
          { level: 5, values: { damage: 776.9 } },
          { level: 6, values: { damage: 832.4 } },
          { level: 7, values: { damage: 906.8 } },
          { level: 8, values: { damage: 981.2 } },
          { level: 9, values: { damage: 1055.6 } },
          { level: 10, values: { damage: 1138.4 } },
        ],
      },
      intro: {
        name: "Waveshock - Intro",
        type: "Intro Skill",
        description: "Rover attacks the target, dealing Spectro DMG.",
        multipliers: [
          { level: 1, values: { damage: 50.0 } },
          { level: 2, values: { damage: 54.1 } },
          { level: 3, values: { damage: 58.2 } },
          { level: 4, values: { damage: 63.9 } },
          { level: 5, values: { damage: 68.0 } },
          { level: 6, values: { damage: 72.8 } },
          { level: 7, values: { damage: 79.3 } },
          { level: 8, values: { damage: 85.8 } },
          { level: 9, values: { damage: 92.3 } },
          { level: 10, values: { damage: 99.6 } },
        ],
      },
      outro: {
        name: "Spectral Blessing",
        type: "Outro Skill",
        description: "The next character gains 23% Spectro DMG Bonus for 15s.",
      },
      passive1: {
        name: "Resonance Mastery",
        description: "When Rover's Resonance Skill hits a target, Rover's ATK is increased by 15% for 8s.",
      },
      passive2: {
        name: "Spectral Harmony",
        description:
          "Rover's Resonance Liberation DMG is increased by 20% when there are 2 or more different elements in the team.",
      },
      concerto: {
        name: "Spectral Convergence",
        description:
          "When the incoming character's (or other characters on a nearby team that activates an Outro Skill) Resonance Skill hits a target, Rover recovers 10 Concerto Energy. This effect can be triggered once every 20s.",
      },
    },
    resonanceChain: [
      "Odyssey of Beginnings: Basic Attack DMG +20%",
      "Microcosmic Murmurs: Resonance Skill DMG +30%",
      "Visages of Dust: Resonance Liberation DMG +40%",
      "Resonating Lamella: All DMG +15%",
      "Temporal Virtuoso: Crit Rate +12%",
      "Echoes of Wandering: Crit DMG +25%",
    ],
  },
  {
    id: "jiyan",
    name: "Jiyan",
    element: "Aero",
    rarity: 5,
    weapon: "Broadblade",
    description:
      "The Midnight Rangers' acting leader. A skilled warrior who wields the power of wind with unmatched precision and grace.",
    baseStats: {
      hp: 866,
      attack: 33,
      defense: 103,
      critRate: 5,
      critDMG: 150,
    },
    skills: {
      basic: {
        name: "Lone Lance",
        type: "Basic Attack",
        description: "Jiyan performs up to 5 consecutive attacks, dealing Aero DMG.",
        multipliers: [
          { level: 1, values: { stage1: 41.8, stage2: 44.64, stage3: 54.43, stage4: 31.71, stage5: 69.25 } },
          { level: 2, values: { stage1: 45.2, stage2: 48.3, stage3: 58.9, stage4: 34.3, stage5: 74.9 } },
          { level: 3, values: { stage1: 48.6, stage2: 51.9, stage3: 63.3, stage4: 36.9, stage5: 80.5 } },
          { level: 4, values: { stage1: 53.4, stage2: 57.0, stage3: 69.5, stage4: 40.5, stage5: 88.4 } },
          { level: 5, values: { stage1: 56.8, stage2: 60.7, stage3: 74.0, stage4: 43.1, stage5: 94.1 } },
          { level: 6, values: { stage1: 60.8, stage2: 65.0, stage3: 79.2, stage4: 46.2, stage5: 100.8 } },
          { level: 7, values: { stage1: 66.2, stage2: 70.8, stage3: 86.3, stage4: 50.3, stage5: 109.8 } },
          { level: 8, values: { stage1: 71.6, stage2: 76.5, stage3: 93.3, stage4: 54.4, stage5: 118.7 } },
          { level: 9, values: { stage1: 77.0, stage2: 82.3, stage3: 100.4, stage4: 58.5, stage5: 127.7 } },
          { level: 10, values: { stage1: 83.0, stage2: 88.7, stage3: 108.2, stage4: 63.1, stage5: 137.7 } },
        ],
      },
      heavy: {
        name: "Lancing Strike",
        type: "Heavy Attack",
        description: "Jiyan consumes Stamina to launch a Plunging Attack, dealing Aero DMG.",
        multipliers: [
          { level: 1, values: { damage: 93.6 } },
          { level: 2, values: { damage: 101.3 } },
          { level: 3, values: { damage: 109.0 } },
          { level: 4, values: { damage: 119.7 } },
          { level: 5, values: { damage: 127.4 } },
          { level: 6, values: { damage: 136.5 } },
          { level: 7, values: { damage: 148.7 } },
          { level: 8, values: { damage: 160.9 } },
          { level: 9, values: { damage: 173.1 } },
          { level: 10, values: { damage: 186.7 } },
        ],
      },
      skill: {
        name: "Windqueller",
        type: "Resonance Skill",
        description: "Dash forward a certain distance, dealing Aero DMG. Can be cast in mid-air.",
        multipliers: [
          { level: 1, values: { damage: 148.32 } },
          { level: 2, values: { damage: 160.4 } },
          { level: 3, values: { damage: 172.5 } },
          { level: 4, values: { damage: 189.4 } },
          { level: 5, values: { damage: 201.5 } },
          { level: 6, values: { damage: 215.8 } },
          { level: 7, values: { damage: 235.1 } },
          { level: 8, values: { damage: 254.4 } },
          { level: 9, values: { damage: 273.7 } },
          { level: 10, values: { damage: 295.1 } },
        ],
      },
      liberation: {
        name: "Emerald Storm: Prelude",
        type: "Resonance Liberation",
        description: "After releasing Resonance Liberation, Jiyan soars into the air and enters Qingloong Mode.",
        multipliers: [
          { level: 1, values: { damage: 178.5, qingloongDamage: 95.55 } },
          { level: 2, values: { damage: 193.1, qingloongDamage: 103.4 } },
          { level: 3, values: { damage: 207.7, qingloongDamage: 111.2 } },
          { level: 4, values: { damage: 228.1, qingloongDamage: 122.1 } },
          { level: 5, values: { damage: 242.7, qingloongDamage: 129.9 } },
          { level: 6, values: { damage: 259.9, qingloongDamage: 139.2 } },
          { level: 7, values: { damage: 283.2, qingloongDamage: 151.7 } },
          { level: 8, values: { damage: 306.5, qingloongDamage: 164.2 } },
          { level: 9, values: { damage: 329.8, qingloongDamage: 176.7 } },
          { level: 10, values: { damage: 355.7, qingloongDamage: 190.6 } },
        ],
      },
      intro: {
        name: "Tactical Strike",
        type: "Intro Skill",
        description: "Jiyan pierces the target in mid-air, dealing Aero DMG.",
        multipliers: [
          { level: 1, values: { damage: 100.0 } },
          { level: 2, values: { damage: 108.2 } },
          { level: 3, values: { damage: 116.4 } },
          { level: 4, values: { damage: 127.8 } },
          { level: 5, values: { damage: 136.0 } },
          { level: 6, values: { damage: 145.6 } },
          { level: 7, values: { damage: 158.6 } },
          { level: 8, values: { damage: 171.6 } },
          { level: 9, values: { damage: 184.6 } },
          { level: 10, values: { damage: 199.2 } },
        ],
      },
      outro: {
        name: "Discipline",
        type: "Outro Skill",
        description: "The next character gains 38% Heavy Attack DMG Bonus for 14s or until the character is switched.",
      },
      passive1: {
        name: "Qingloong at War",
        description: "In Qingloong Mode, Jiyan's Aero DMG is increased by 20%.",
      },
      passive2: {
        name: "Tempest Taming",
        description:
          "When Jiyan's Heavy Attack hits a target, his ATK is increased by 10% for 8s, stacking up to 3 times.",
      },
      concerto: {
        name: "Discipline",
        description:
          "When the incoming character's (or other characters on a nearby team that activates an Outro Skill) Heavy Attack hits a target, Jiyan recovers 10 Concerto Energy. This effect can be triggered once every 20s.",
      },
    },
    resonanceChain: [
      "Benevolence: Resonance Skill DMG +28%",
      "Versatility: After casting Intro Skill, ATK +28% for 15s",
      "Serenity: Resonance Liberation DMG +32%",
      "Prudence: When casting Resonance Liberation, ATK +25% for 25s",
      "Resolution: Crit DMG +50% for 30s after casting Resonance Liberation",
      "Fortitude: Every time Heavy Attack hits a target, next Resonance Liberation DMG +120%",
    ],
  },
  {
    id: "calcharo",
    name: "Calcharo",
    element: "Electro",
    rarity: 5,
    weapon: "Broadblade",
    description:
      "Leader of the Ghost Hounds mercenary organization. A cold and calculating warrior who strikes from the shadows.",
    baseStats: {
      hp: 825,
      attack: 36,
      defense: 98,
      critRate: 5,
      critDMG: 150,
    },
    skills: {
      basic: {
        name: "Gnawing Fangs",
        type: "Basic Attack",
        description: "Calcharo performs up to 4 consecutive attacks, dealing Electro DMG.",
        multipliers: [
          { level: 1, values: { stage1: 50.31, stage2: 44.64, stage3: 54.43, stage4: 89.25 } },
          { level: 2, values: { stage1: 54.4, stage2: 48.3, stage3: 58.9, stage4: 96.5 } },
          { level: 3, values: { stage1: 58.5, stage2: 51.9, stage3: 63.3, stage4: 103.8 } },
          { level: 4, values: { stage1: 64.2, stage2: 57.0, stage3: 69.5, stage4: 114.0 } },
          { level: 5, values: { stage1: 68.3, stage2: 60.7, stage3: 74.0, stage4: 121.3 } },
          { level: 6, values: { stage1: 73.2, stage2: 65.0, stage3: 79.2, stage4: 129.9 } },
          { level: 7, values: { stage1: 79.7, stage2: 70.8, stage3: 86.3, stage4: 141.5 } },
          { level: 8, values: { stage1: 86.2, stage2: 76.5, stage3: 93.3, stage4: 153.1 } },
          { level: 9, values: { stage1: 92.7, stage2: 82.3, stage3: 100.4, stage4: 164.7 } },
          { level: 10, values: { stage1: 100.0, stage2: 88.7, stage3: 108.2, stage4: 177.6 } },
        ],
      },
      heavy: {
        name: "Hunting Mission",
        type: "Heavy Attack",
        description: "Calcharo consumes Stamina to perform a Plunging Attack, dealing Electro DMG.",
        multipliers: [
          { level: 1, values: { damage: 62.5 } },
          { level: 2, values: { damage: 67.6 } },
          { level: 3, values: { damage: 72.7 } },
          { level: 4, values: { damage: 79.8 } },
          { level: 5, values: { damage: 84.9 } },
          { level: 6, values: { damage: 91.0 } },
          { level: 7, values: { damage: 99.1 } },
          { level: 8, values: { damage: 107.2 } },
          { level: 9, values: { damage: 115.3 } },
          { level: 10, values: { damage: 124.4 } },
        ],
      },
      skill: {
        name: "Extermination Order",
        type: "Resonance Skill",
        description: "Calcharo performs a fast Electro attack, dealing Electro DMG.",
        multipliers: [
          { level: 1, values: { damage: 142.8 } },
          { level: 2, values: { damage: 154.4 } },
          { level: 3, values: { damage: 166.0 } },
          { level: 4, values: { damage: 182.2 } },
          { level: 5, values: { damage: 193.8 } },
          { level: 6, values: { damage: 207.5 } },
          { level: 7, values: { damage: 226.1 } },
          { level: 8, values: { damage: 244.7 } },
          { level: 9, values: { damage: 263.3 } },
          { level: 10, values: { damage: 284.0 } },
        ],
      },
      liberation: {
        name: "Phantom Etching",
        type: "Resonance Liberation",
        description: "Calcharo attacks all nearby enemies, dealing massive Electro DMG.",
        multipliers: [
          { level: 1, values: { damage: 571.2 } },
          { level: 2, values: { damage: 618.0 } },
          { level: 3, values: { damage: 664.8 } },
          { level: 4, values: { damage: 730.1 } },
          { level: 5, values: { damage: 776.9 } },
          { level: 6, values: { damage: 832.4 } },
          { level: 7, values: { damage: 906.8 } },
          { level: 8, values: { damage: 981.2 } },
          { level: 9, values: { damage: 1055.6 } },
          { level: 10, values: { damage: 1138.4 } },
        ],
      },
      intro: {
        name: "Wanted Outlaw",
        type: "Intro Skill",
        description: "Calcharo attacks the target, dealing Electro DMG.",
        multipliers: [
          { level: 1, values: { damage: 100.0 } },
          { level: 2, values: { damage: 108.2 } },
          { level: 3, values: { damage: 116.4 } },
          { level: 4, values: { damage: 127.8 } },
          { level: 5, values: { damage: 136.0 } },
          { level: 6, values: { damage: 145.6 } },
          { level: 7, values: { damage: 158.6 } },
          { level: 8, values: { damage: 171.6 } },
          { level: 9, values: { damage: 184.6 } },
          { level: 10, values: { damage: 199.2 } },
        ],
      },
      outro: {
        name: "Shadowy Raid",
        type: "Outro Skill",
        description:
          "The next character gains 12% Electro DMG Bonus and 12% Resonance Liberation DMG Bonus for 14s or until the character is switched.",
      },
      passive1: {
        name: "Hunting Instinct",
        description: "When Calcharo's Resonance Skill hits a target, his Crit Rate is increased by 15% for 8s.",
      },
      passive2: {
        name: "Mercy",
        description:
          "When Calcharo's Heavy Attack hits a target, his next Resonance Liberation DMG is increased by 25%.",
      },
      concerto: {
        name: "Shadowy Raid",
        description:
          "When the incoming character's (or other characters on a nearby team that activates an Outro Skill) Resonance Liberation hits a target, Calcharo recovers 10 Concerto Energy. This effect can be triggered once every 20s.",
      },
    },
    resonanceChain: [
      "Covert Operation: Intro Skill DMG +100%",
      "Preparation: Resonance Skill DMG +25%",
      "Execution: Resonance Liberation DMG +35%",
      "Camouflage: When Resonance Liberation hits a target, ATK +25% for 27s",
      "Coordination: Crit Rate +25% for 27s after casting Resonance Liberation",
      "Annihilation: Resonance Liberation Crit DMG +25%. After casting Resonance Liberation, ATK +25% for 30s",
    ],
  },
]

export const weapons = [
  {
    id: "emerald-of-genesis",
    name: "Emerald of Genesis",
    type: "Sword",
    rarity: 5,
    baseAttack: 587,
    subStat: "Crit Rate",
    subStatValue: 22.1,
    passive:
      "ATK increased by 12%. After releasing Basic Attack or Heavy Attack, ATK will be increased by 6% for 8s, stacking up to 2 times.",
    passiveStats: { atkPercent: 12 },
  },
  {
    id: "verdant-summit",
    name: "Verdant Summit",
    type: "Broadblade",
    rarity: 5,
    baseAttack: 587,
    subStat: "Crit DMG",
    subStatValue: 44.2,
    passive:
      "ATK increased by 12%. After releasing Heavy Attack or Resonance Skill, ATK will be increased by 6% for 8s, stacking up to 2 times.",
    passiveStats: { atkPercent: 12 },
  },
  {
    id: "thundering-mephis",
    name: "Thundering Mephis",
    type: "Broadblade",
    rarity: 5,
    baseAttack: 587,
    subStat: "ATK%",
    subStatValue: 33.1,
    passive:
      "ATK increased by 12%. After releasing Resonance Skill, the next Resonance Liberation DMG dealt will be increased by 48%.",
    passiveStats: { atkPercent: 12 },
  },
  {
    id: "ages-of-harvest",
    name: "Ages of Harvest",
    type: "Broadblade",
    rarity: 4,
    baseAttack: 412,
    subStat: "ATK%",
    subStatValue: 36.4,
    passive: "ATK increased by 12%. Casting Resonance Skill grants 3% ATK, stacking up to 7 times for 7s.",
    passiveStats: { atkPercent: 12 },
  },
  {
    id: "lunar-cutter",
    name: "Lunar Cutter",
    type: "Sword",
    rarity: 4,
    baseAttack: 412,
    subStat: "ATK%",
    subStatValue: 36.4,
    passive: "ATK increased by 12%. Basic Attack DMG increased by 24%.",
    passiveStats: { atkPercent: 12 },
  },
  {
    id: "cosmic-ripples",
    name: "Cosmic Ripples",
    type: "Rectifier",
    rarity: 5,
    baseAttack: 587,
    subStat: "Energy Regen",
    subStatValue: 32.4,
    passive: "Energy Regen increased by 12.8%. Casting Resonance Skill increases ATK by 12% for 15s.",
    passiveStats: { energyRegen: 12.8 },
  },
  {
    id: "stringmaster",
    name: "Stringmaster",
    type: "Rectifier",
    rarity: 4,
    baseAttack: 412,
    subStat: "Crit Rate",
    subStatValue: 24.3,
    passive: "ATK increased by 12%. Resonance Skill DMG increased by 24%.",
    passiveStats: { atkPercent: 12 },
  },
  {
    id: "abyss-surges",
    name: "Abyss Surges",
    type: "Gauntlets",
    rarity: 5,
    baseAttack: 587,
    subStat: "Crit DMG",
    subStatValue: 44.2,
    passive: "ATK increased by 12%. Normal Attack DMG increased by 24%.",
    passiveStats: { atkPercent: 12 },
  },
  {
    id: "gauntlets-of-night",
    name: "Gauntlets of Night",
    type: "Gauntlets",
    rarity: 4,
    baseAttack: 412,
    subStat: "Crit Rate",
    subStatValue: 24.3,
    passive: "ATK increased by 12%. Heavy Attack DMG increased by 36%.",
    passiveStats: { atkPercent: 12 },
  },
]

export const echoSets = [
  {
    id: "freezing-frost",
    name: "Freezing Frost",
    element: "Glacio",
    bonuses: {
      "2pc": "Glacio DMG +10%",
      "5pc":
        "After releasing Basic Attack or Heavy Attack, ATK will be increased by 12% for 15s, stacking up to 2 times.",
    },
    mainStats: {
      4: ["ATK%", "Glacio DMG%", "Healing Bonus%", "Crit Rate", "Crit DMG"],
      3: ["ATK%", "HP%", "DEF%", "Energy Regen", "Glacio DMG%"],
      1: ["ATK%", "HP%", "DEF%"],
    },
  },
  {
    id: "molten-rift",
    name: "Molten Rift",
    element: "Fusion",
    bonuses: {
      "2pc": "Fusion DMG +10%",
      "5pc": "After releasing Resonance Liberation, ATK will be increased by 20% for 15s.",
    },
    mainStats: {
      4: ["ATK%", "Fusion DMG%", "Healing Bonus%", "Crit Rate", "Crit DMG"],
      3: ["ATK%", "HP%", "DEF%", "Energy Regen", "Fusion DMG%"],
      1: ["ATK%", "HP%", "DEF%"],
    },
  },
  {
    id: "void-thunder",
    name: "Void Thunder",
    element: "Electro",
    bonuses: {
      "2pc": "Electro DMG +10%",
      "5pc": "After releasing Heavy Attack or Resonance Skill, ATK will be increased by 15% for 15s.",
    },
    mainStats: {
      4: ["ATK%", "Electro DMG%", "Healing Bonus%", "Crit Rate", "Crit DMG"],
      3: ["ATK%", "HP%", "DEF%", "Energy Regen", "Electro DMG%"],
      1: ["ATK%", "HP%", "DEF%"],
    },
  },
  {
    id: "sierra-gale",
    name: "Sierra Gale",
    element: "Aero",
    bonuses: {
      "2pc": "Aero DMG +10%",
      "5pc": "ATK will be increased by 30% for 15s when casting Intro Skill.",
    },
    mainStats: {
      4: ["ATK%", "Aero DMG%", "Healing Bonus%", "Crit Rate", "Crit DMG"],
      3: ["ATK%", "HP%", "DEF%", "Energy Regen", "Aero DMG%"],
      1: ["ATK%", "HP%", "DEF%"],
    },
  },
  {
    id: "celestial-light",
    name: "Celestial Light",
    element: "Spectro",
    bonuses: {
      "2pc": "Spectro DMG +10%",
      "5pc": "After releasing Intro Skill, ATK will be increased by 15% for 15s.",
    },
    mainStats: {
      4: ["ATK%", "Spectro DMG%", "Healing Bonus%", "Crit Rate", "Crit DMG"],
      3: ["ATK%", "HP%", "DEF%", "Energy Regen", "Spectro DMG%"],
      1: ["ATK%", "HP%", "DEF%"],
    },
  },
  {
    id: "rejuvenating-glow",
    name: "Rejuvenating Glow",
    element: "Healing",
    bonuses: {
      "2pc": "Healing Bonus +10%",
      "5pc": "After healing a target, increases the entire team's ATK by 15% for 30s.",
    },
    mainStats: {
      4: ["ATK%", "Healing Bonus%", "HP%", "Crit Rate", "Crit DMG"],
      3: ["ATK%", "HP%", "DEF%", "Energy Regen", "Healing Bonus%"],
      1: ["ATK%", "HP%", "DEF%"],
    },
  },
  {
    id: "moonlit-clouds",
    name: "Moonlit Clouds",
    element: "Support",
    bonuses: {
      "2pc": "Energy Regen +10%",
      "5pc": "After using Outro Skill, the next character's DMG dealt will be increased by 12% for 15s.",
    },
    mainStats: {
      4: ["ATK%", "Energy Regen", "HP%", "Crit Rate", "Crit DMG"],
      3: ["ATK%", "HP%", "DEF%", "Energy Regen"],
      1: ["ATK%", "HP%", "DEF%"],
    },
  },
  {
    id: "lingering-tunes",
    name: "Lingering Tunes",
    element: "Universal",
    bonuses: {
      "2pc": "ATK +12%",
      "5pc":
        "While on the field, ATK will be increased by 5% every 1.5s. This effect stacks up to 4 times and will be reset when the character leaves the field.",
    },
    mainStats: {
      4: ["ATK%", "HP%", "DEF%", "Crit Rate", "Crit DMG"],
      3: ["ATK%", "HP%", "DEF%", "Energy Regen"],
      1: ["ATK%", "HP%", "DEF%"],
    },
  },
  {
    id: "empyrean-anthem",
    name: "Empyrean Anthem",
    element: "Support",
    bonuses: {
      "2pc": "Energy Regen +10%",
      "5pc": "Increase the Outro Skill DMG of all team members by 20%.",
    },
    mainStats: {
      4: ["ATK%", "Energy Regen", "HP%", "Crit Rate", "Crit DMG"],
      3: ["ATK%", "HP%", "DEF%", "Energy Regen"],
      1: ["ATK%", "HP%", "DEF%"],
    },
  },
  {
    id: "frosty-resolve",
    name: "Frosty Resolve",
    element: "Glacio",
    bonuses: {
      "2pc": "Glacio DMG +10%",
      "5pc": "When Basic Attack or Heavy Attack hits a target, Crit Rate will be increased by 12% for 15s.",
    },
    mainStats: {
      4: ["ATK%", "Glacio DMG%", "Crit Rate", "Crit DMG"],
      3: ["ATK%", "HP%", "DEF%", "Energy Regen", "Glacio DMG%"],
      1: ["ATK%", "HP%", "DEF%"],
    },
  },
]

export const echoes = [
  {
    id: "freezing-frost",
    name: "Freezing Frost",
    element: "Glacio",
    cost: 4,
    setBonus: {
      "2pc": "Glacio DMG +10%",
      "5pc":
        "After releasing Basic Attack or Heavy Attack, ATK will be increased by 12% for 15s, stacking up to 2 times.",
    },
    mainStats: ["ATK%", "Glacio DMG%", "Healing Bonus%", "Crit Rate", "Crit DMG"],
    subStats: [
      "ATK",
      "ATK%",
      "HP",
      "HP%",
      "DEF",
      "DEF%",
      "Crit Rate",
      "Crit DMG",
      "Energy Regen",
      "Basic Attack DMG%",
      "Heavy Attack DMG%",
      "Resonance Skill DMG%",
      "Resonance Liberation DMG%",
    ],
  },
  {
    id: "molten-rift",
    name: "Molten Rift",
    element: "Fusion",
    cost: 4,
    setBonus: {
      "2pc": "Fusion DMG +10%",
      "5pc": "After releasing Resonance Liberation, ATK will be increased by 20% for 15s.",
    },
    mainStats: ["ATK%", "Fusion DMG%", "Healing Bonus%", "Crit Rate", "Crit DMG"],
    subStats: [
      "ATK",
      "ATK%",
      "HP",
      "HP%",
      "DEF",
      "DEF%",
      "Crit Rate",
      "Crit DMG",
      "Energy Regen",
      "Basic Attack DMG%",
      "Heavy Attack DMG%",
      "Resonance Skill DMG%",
      "Resonance Liberation DMG%",
    ],
  },
  {
    id: "void-thunder",
    name: "Void Thunder",
    element: "Electro",
    cost: 4,
    setBonus: {
      "2pc": "Electro DMG +10%",
      "5pc": "After releasing Heavy Attack or Resonance Skill, ATK will be increased by 15% for 15s.",
    },
    mainStats: ["ATK%", "Electro DMG%", "Healing Bonus%", "Crit Rate", "Crit DMG"],
    subStats: [
      "ATK",
      "ATK%",
      "HP",
      "HP%",
      "DEF",
      "DEF%",
      "Crit Rate",
      "Crit DMG",
      "Energy Regen",
      "Basic Attack DMG%",
      "Heavy Attack DMG%",
      "Resonance Skill DMG%",
      "Resonance Liberation DMG%",
    ],
  },
  {
    id: "sierra-gale",
    name: "Sierra Gale",
    element: "Aero",
    cost: 4,
    setBonus: {
      "2pc": "Aero DMG +10%",
      "5pc": "ATK will be increased by 30% for 15s when casting Intro Skill.",
    },
    mainStats: ["ATK%", "Aero DMG%", "Healing Bonus%", "Crit Rate", "Crit DMG"],
    subStats: [
      "ATK",
      "ATK%",
      "HP",
      "HP%",
      "DEF",
      "DEF%",
      "Crit Rate",
      "Crit DMG",
      "Energy Regen",
      "Basic Attack DMG%",
      "Heavy Attack DMG%",
      "Resonance Skill DMG%",
      "Resonance Liberation DMG%",
    ],
  },
  {
    id: "celestial-light",
    name: "Celestial Light",
    element: "Spectro",
    cost: 4,
    setBonus: {
      "2pc": "Spectro DMG +10%",
      "5pc": "After releasing Intro Skill, ATK will be increased by 15% for 15s.",
    },
    mainStats: ["ATK%", "Spectro DMG%", "Healing Bonus%", "Crit Rate", "Crit DMG"],
    subStats: [
      "ATK",
      "ATK%",
      "HP",
      "HP%",
      "DEF",
      "DEF%",
      "Crit Rate",
      "Crit DMG",
      "Energy Regen",
      "Basic Attack DMG%",
      "Heavy Attack DMG%",
      "Resonance Skill DMG%",
      "Resonance Liberation DMG%",
    ],
  },
  {
    id: "rejuvenating-glow",
    name: "Rejuvenating Glow",
    element: "Healing",
    cost: 4,
    setBonus: {
      "2pc": "Healing Bonus +10%",
      "5pc": "After healing a target, increases the entire team's ATK by 15% for 30s.",
    },
    mainStats: ["ATK%", "Healing Bonus%", "HP%", "Crit Rate", "Crit DMG"],
    subStats: [
      "ATK",
      "ATK%",
      "HP",
      "HP%",
      "DEF",
      "DEF%",
      "Crit Rate",
      "Crit DMG",
      "Energy Regen",
      "Basic Attack DMG%",
      "Heavy Attack DMG%",
      "Resonance Skill DMG%",
      "Resonance Liberation DMG%",
    ],
  },
  {
    id: "moonlit-clouds",
    name: "Moonlit Clouds",
    element: "Support",
    cost: 4,
    setBonus: {
      "2pc": "Energy Regen +10%",
      "5pc": "After using Outro Skill, the next character's DMG dealt will be increased by 12% for 15s.",
    },
    mainStats: ["ATK%", "Energy Regen", "HP%", "Crit Rate", "Crit DMG"],
    subStats: [
      "ATK",
      "ATK%",
      "HP",
      "HP%",
      "DEF",
      "DEF%",
      "Crit Rate",
      "Crit DMG",
      "Energy Regen",
      "Basic Attack DMG%",
      "Heavy Attack DMG%",
      "Resonance Skill DMG%",
      "Resonance Liberation DMG%",
    ],
  },
  {
    id: "lingering-tunes",
    name: "Lingering Tunes",
    element: "Universal",
    cost: 4,
    setBonus: {
      "2pc": "ATK +12%",
      "5pc":
        "While on the field, ATK will be increased by 5% every 1.5s. This effect stacks up to 4 times and will be reset when the character leaves the field.",
    },
    mainStats: ["ATK%", "HP%", "DEF%", "Crit Rate", "Crit DMG"],
    subStats: [
      "ATK",
      "ATK%",
      "HP",
      "HP%",
      "DEF",
      "DEF%",
      "Crit Rate",
      "Crit DMG",
      "Energy Regen",
      "Basic Attack DMG%",
      "Heavy Attack DMG%",
      "Resonance Skill DMG%",
      "Resonance Liberation DMG%",
    ],
  },
  {
    id: "empyrean-anthem",
    name: "Empyrean Anthem",
    element: "Support",
    cost: 4,
    setBonus: {
      "2pc": "Energy Regen +10%",
      "5pc": "Increase the Outro Skill DMG of all team members by 20%.",
    },
    mainStats: ["ATK%", "Energy Regen", "HP%", "Crit Rate", "Crit DMG"],
    subStats: [
      "ATK",
      "ATK%",
      "HP",
      "HP%",
      "DEF",
      "DEF%",
      "Crit Rate",
      "Crit DMG",
      "Energy Regen",
      "Basic Attack DMG%",
      "Heavy Attack DMG%",
      "Resonance Skill DMG%",
      "Resonance Liberation DMG%",
    ],
  },
  {
    id: "frosty-resolve",
    name: "Frosty Resolve",
    element: "Glacio",
    cost: 4,
    setBonus: {
      "2pc": "Glacio DMG +10%",
      "5pc": "When Basic Attack or Heavy Attack hits a target, Crit Rate will be increased by 12% for 15s.",
    },
    mainStats: ["ATK%", "Glacio DMG%", "Crit Rate", "Crit DMG"],
    subStats: [
      "ATK",
      "ATK%",
      "HP",
      "HP%",
      "DEF",
      "DEF%",
      "Crit Rate",
      "Crit DMG",
      "Energy Regen",
      "Basic Attack DMG%",
      "Heavy Attack DMG%",
      "Resonance Skill DMG%",
      "Resonance Liberation DMG%",
    ],
  },
]

export const echoMainStatRanges = {
  4: {
    "ATK%": { min: 30, max: 33 },
    "HP%": { min: 30, max: 33 },
    "DEF%": { min: 38, max: 41.3 },
    "Crit Rate": { min: 18, max: 22 },
    "Crit DMG": { min: 36, max: 44 },
    "Healing Bonus%": { min: 26, max: 33 },
    "Energy Regen": { min: 26, max: 32 },
    "Glacio DMG%": { min: 30, max: 33 },
    "Fusion DMG%": { min: 30, max: 33 },
    "Electro DMG%": { min: 30, max: 33 },
    "Aero DMG%": { min: 30, max: 33 },
    "Spectro DMG%": { min: 30, max: 33 },
    "Havoc DMG%": { min: 30, max: 33 },
  },
  3: {
    "ATK%": { min: 30, max: 33 },
    "HP%": { min: 30, max: 33 },
    "DEF%": { min: 38, max: 41.3 },
    "Energy Regen": { min: 26, max: 32 },
    "Glacio DMG%": { min: 30, max: 33 },
    "Fusion DMG%": { min: 30, max: 33 },
    "Electro DMG%": { min: 30, max: 33 },
    "Aero DMG%": { min: 30, max: 33 },
    "Spectro DMG%": { min: 30, max: 33 },
    "Havoc DMG%": { min: 30, max: 33 },
  },
  1: {
    "ATK%": { min: 30, max: 33 },
    "HP%": { min: 30, max: 33 },
    "DEF%": { min: 38, max: 41.3 },
  },
}

export const echoSubStatRanges = {
  ATK: { min: 30, max: 50 },
  "ATK%": { min: 6.4, max: 8.1 },
  HP: { min: 320, max: 580 },
  "HP%": { min: 6.4, max: 8.1 },
  DEF: { min: 40, max: 67 },
  "DEF%": { min: 8.1, max: 10.1 },
  "Crit Rate": { min: 6.3, max: 8.4 },
  "Crit DMG": { min: 12.6, max: 16.8 },
  "Energy Regen": { min: 6.8, max: 9.1 },
  "Basic Attack DMG%": { min: 6.4, max: 8.1 },
  "Heavy Attack DMG%": { min: 6.4, max: 8.1 },
  "Resonance Skill DMG%": { min: 6.4, max: 8.1 },
  "Resonance Liberation DMG%": { min: 6.4, max: 8.1 },
}

export const materials = {
  characterAscension: [
    { name: "LF Whisperin Core", rarity: 1 },
    { name: "MF Whisperin Core", rarity: 2 },
    { name: "HF Whisperin Core", rarity: 3 },
    { name: "FF Whisperin Core", rarity: 4 },
    { name: "Shell Credits", rarity: 1 },
  ],
  weaponAscension: [
    { name: "Crude Ring", rarity: 1 },
    { name: "Basic Ring", rarity: 2 },
    { name: "Improved Ring", rarity: 3 },
    { name: "Tailored Ring", rarity: 4 },
  ],
  skillUpgrade: [
    { name: "Waveworn Residue 210", rarity: 2 },
    { name: "Waveworn Residue 226", rarity: 3 },
    { name: "Waveworn Residue 235", rarity: 4 },
    { name: "Waveworn Residue 239", rarity: 5 },
  ],
}
